/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface AnimalControllerCreateRequest {
    body: object;
}

export interface AnimalControllerFindAllRequest {
    species?: AnimalControllerFindAllSpeciesEnum;
}

export interface AnimalControllerFindOneRequest {
    id: number;
}

export interface AnimalControllerRemoveRequest {
    id: number;
}

export interface AnimalControllerUpdateRequest {
    id: number;
    body: object;
}

/**
 * 
 */
export class AnimalsApi extends runtime.BaseAPI {

    /**
     * Enregistrer un nouvel animal
     */
    async animalControllerCreateRaw(requestParameters: AnimalControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling animalControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/animals`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Enregistrer un nouvel animal
     */
    async animalControllerCreate(requestParameters: AnimalControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.animalControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Récupérer tous les animaux avec pagination et recherche
     */
    async animalControllerFindAllRaw(requestParameters: AnimalControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['species'] != null) {
            queryParameters['species'] = requestParameters['species'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/animals`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Récupérer tous les animaux avec pagination et recherche
     */
    async animalControllerFindAll(requestParameters: AnimalControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.animalControllerFindAllRaw(requestParameters, initOverrides);
    }

    /**
     * Récupérer un animal par son ID
     */
    async animalControllerFindOneRaw(requestParameters: AnimalControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling animalControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/animals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Récupérer un animal par son ID
     */
    async animalControllerFindOne(requestParameters: AnimalControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.animalControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Supprimer un animal
     */
    async animalControllerRemoveRaw(requestParameters: AnimalControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling animalControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/animals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Supprimer un animal
     */
    async animalControllerRemove(requestParameters: AnimalControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.animalControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Modifier les informations d\'un animal
     */
    async animalControllerUpdateRaw(requestParameters: AnimalControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling animalControllerUpdate().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling animalControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/animals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Modifier les informations d\'un animal
     */
    async animalControllerUpdate(requestParameters: AnimalControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.animalControllerUpdateRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const AnimalControllerFindAllSpeciesEnum = {
    Chien: 'chien',
    Chat: 'chat',
    Hamster: 'hamster',
    Tortue: 'tortue'
} as const;
export type AnimalControllerFindAllSpeciesEnum = typeof AnimalControllerFindAllSpeciesEnum[keyof typeof AnimalControllerFindAllSpeciesEnum];
