/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class CommonApi extends runtime.BaseAPI {

    /**
     * Récupérer la liste des civilités
     */
    async commonControllerGetCivilitiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/common/civilities`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Récupérer la liste des civilités
     */
    async commonControllerGetCivilities(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.commonControllerGetCivilitiesRaw(initOverrides);
    }

    /**
     * Récupérer la liste des espèces d\'animaux
     */
    async commonControllerGetSpeciesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/common/species`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Récupérer la liste des espèces d\'animaux
     */
    async commonControllerGetSpecies(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.commonControllerGetSpeciesRaw(initOverrides);
    }

}
