/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnimalControllerCreate201Response,
  AnimalControllerFindAll200Response,
  CreateAnimalDto,
  UpdateAnimalDto,
} from '../models/index';
import {
    AnimalControllerCreate201ResponseFromJSON,
    AnimalControllerCreate201ResponseToJSON,
    AnimalControllerFindAll200ResponseFromJSON,
    AnimalControllerFindAll200ResponseToJSON,
    CreateAnimalDtoFromJSON,
    CreateAnimalDtoToJSON,
    UpdateAnimalDtoFromJSON,
    UpdateAnimalDtoToJSON,
} from '../models/index';

export interface AnimalControllerCreateRequest {
    createAnimalDto: CreateAnimalDto;
}

export interface AnimalControllerFindAllRequest {
    page?: number;
    limit?: number;
    search?: string;
    species?: AnimalControllerFindAllSpeciesEnum;
}

export interface AnimalControllerFindOneRequest {
    id: number;
}

export interface AnimalControllerRemoveRequest {
    id: number;
}

export interface AnimalControllerUpdateRequest {
    id: number;
    updateAnimalDto: UpdateAnimalDto;
}

/**
 * 
 */
export class AnimalsApi extends runtime.BaseAPI {

    /**
     * Enregistrer un nouvel animal
     */
    async animalControllerCreateRaw(requestParameters: AnimalControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnimalControllerCreate201Response>> {
        if (requestParameters['createAnimalDto'] == null) {
            throw new runtime.RequiredError(
                'createAnimalDto',
                'Required parameter "createAnimalDto" was null or undefined when calling animalControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/animals`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAnimalDtoToJSON(requestParameters['createAnimalDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnimalControllerCreate201ResponseFromJSON(jsonValue));
    }

    /**
     * Enregistrer un nouvel animal
     */
    async animalControllerCreate(requestParameters: AnimalControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnimalControllerCreate201Response> {
        const response = await this.animalControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Récupérer tous les animaux avec pagination et recherche
     */
    async animalControllerFindAllRaw(requestParameters: AnimalControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnimalControllerFindAll200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['species'] != null) {
            queryParameters['species'] = requestParameters['species'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/animals`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnimalControllerFindAll200ResponseFromJSON(jsonValue));
    }

    /**
     * Récupérer tous les animaux avec pagination et recherche
     */
    async animalControllerFindAll(requestParameters: AnimalControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnimalControllerFindAll200Response> {
        const response = await this.animalControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Récupérer un animal par son ID
     */
    async animalControllerFindOneRaw(requestParameters: AnimalControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnimalControllerCreate201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling animalControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/animals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnimalControllerCreate201ResponseFromJSON(jsonValue));
    }

    /**
     * Récupérer un animal par son ID
     */
    async animalControllerFindOne(requestParameters: AnimalControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnimalControllerCreate201Response> {
        const response = await this.animalControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Supprimer un animal
     */
    async animalControllerRemoveRaw(requestParameters: AnimalControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling animalControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/animals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Supprimer un animal
     */
    async animalControllerRemove(requestParameters: AnimalControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.animalControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Modifier les informations d\'un animal
     */
    async animalControllerUpdateRaw(requestParameters: AnimalControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnimalControllerCreate201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling animalControllerUpdate().'
            );
        }

        if (requestParameters['updateAnimalDto'] == null) {
            throw new runtime.RequiredError(
                'updateAnimalDto',
                'Required parameter "updateAnimalDto" was null or undefined when calling animalControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/animals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAnimalDtoToJSON(requestParameters['updateAnimalDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnimalControllerCreate201ResponseFromJSON(jsonValue));
    }

    /**
     * Modifier les informations d\'un animal
     */
    async animalControllerUpdate(requestParameters: AnimalControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnimalControllerCreate201Response> {
        const response = await this.animalControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AnimalControllerFindAllSpeciesEnum = {
    Chien: 'chien',
    Chat: 'chat',
    Hamster: 'hamster',
    Tortue: 'tortue'
} as const;
export type AnimalControllerFindAllSpeciesEnum = typeof AnimalControllerFindAllSpeciesEnum[keyof typeof AnimalControllerFindAllSpeciesEnum];
