/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Client,
  CreateClientDto,
  PaginatedClientResponseDto,
  UpdateClientDto,
} from '../models/index';
import {
    ClientFromJSON,
    ClientToJSON,
    CreateClientDtoFromJSON,
    CreateClientDtoToJSON,
    PaginatedClientResponseDtoFromJSON,
    PaginatedClientResponseDtoToJSON,
    UpdateClientDtoFromJSON,
    UpdateClientDtoToJSON,
} from '../models/index';

export interface ClientControllerCreateRequest {
    createClientDto: CreateClientDto;
}

export interface ClientControllerFindAllRequest {
    page?: number;
    limit?: number;
    search?: string;
}

export interface ClientControllerFindOneRequest {
    id: number;
}

export interface ClientControllerRemoveRequest {
    id: number;
}

export interface ClientControllerUpdateRequest {
    id: number;
    updateClientDto: UpdateClientDto;
}

/**
 * 
 */
export class ClientsApi extends runtime.BaseAPI {

    /**
     * Créer un nouveau client
     */
    async clientControllerCreateRaw(requestParameters: ClientControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Client>> {
        if (requestParameters['createClientDto'] == null) {
            throw new runtime.RequiredError(
                'createClientDto',
                'Required parameter "createClientDto" was null or undefined when calling clientControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/clients`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateClientDtoToJSON(requestParameters['createClientDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientFromJSON(jsonValue));
    }

    /**
     * Créer un nouveau client
     */
    async clientControllerCreate(requestParameters: ClientControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Client> {
        const response = await this.clientControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Récupérer tous les clients avec pagination et recherche
     */
    async clientControllerFindAllRaw(requestParameters: ClientControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedClientResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/clients`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedClientResponseDtoFromJSON(jsonValue));
    }

    /**
     * Récupérer tous les clients avec pagination et recherche
     */
    async clientControllerFindAll(requestParameters: ClientControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedClientResponseDto> {
        const response = await this.clientControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Récupérer un client par son ID
     */
    async clientControllerFindOneRaw(requestParameters: ClientControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Client>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling clientControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/clients/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientFromJSON(jsonValue));
    }

    /**
     * Récupérer un client par son ID
     */
    async clientControllerFindOne(requestParameters: ClientControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Client> {
        const response = await this.clientControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Supprimer un client
     */
    async clientControllerRemoveRaw(requestParameters: ClientControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling clientControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/clients/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Supprimer un client
     */
    async clientControllerRemove(requestParameters: ClientControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.clientControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Modifier un client
     */
    async clientControllerUpdateRaw(requestParameters: ClientControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Client>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling clientControllerUpdate().'
            );
        }

        if (requestParameters['updateClientDto'] == null) {
            throw new runtime.RequiredError(
                'updateClientDto',
                'Required parameter "updateClientDto" was null or undefined when calling clientControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/clients/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateClientDtoToJSON(requestParameters['updateClientDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientFromJSON(jsonValue));
    }

    /**
     * Modifier un client
     */
    async clientControllerUpdate(requestParameters: ClientControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Client> {
        const response = await this.clientControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
