/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Animal } from './Animal';
import {
    AnimalFromJSON,
    AnimalFromJSONTyped,
    AnimalToJSON,
} from './Animal';
import type { MetaDto } from './MetaDto';
import {
    MetaDtoFromJSON,
    MetaDtoFromJSONTyped,
    MetaDtoToJSON,
} from './MetaDto';

/**
 * 
 * @export
 * @interface AnimalControllerCreate201Response
 */
export interface AnimalControllerCreate201Response {
    /**
     * 
     * @type {Animal}
     * @memberof AnimalControllerCreate201Response
     */
    data: Animal;
    /**
     * 
     * @type {MetaDto}
     * @memberof AnimalControllerCreate201Response
     */
    meta: MetaDto;
}

/**
 * Check if a given object implements the AnimalControllerCreate201Response interface.
 */
export function instanceOfAnimalControllerCreate201Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function AnimalControllerCreate201ResponseFromJSON(json: any): AnimalControllerCreate201Response {
    return AnimalControllerCreate201ResponseFromJSONTyped(json, false);
}

export function AnimalControllerCreate201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnimalControllerCreate201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AnimalFromJSON(json['data']),
        'meta': MetaDtoFromJSON(json['meta']),
    };
}

export function AnimalControllerCreate201ResponseToJSON(value?: AnimalControllerCreate201Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': AnimalToJSON(value['data']),
        'meta': MetaDtoToJSON(value['meta']),
    };
}

