/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaDto } from './MetaDto';
import {
    MetaDtoFromJSON,
    MetaDtoFromJSONTyped,
    MetaDtoToJSON,
} from './MetaDto';
import type { PaginatedAnimalResponseDto } from './PaginatedAnimalResponseDto';
import {
    PaginatedAnimalResponseDtoFromJSON,
    PaginatedAnimalResponseDtoFromJSONTyped,
    PaginatedAnimalResponseDtoToJSON,
} from './PaginatedAnimalResponseDto';

/**
 * 
 * @export
 * @interface AnimalControllerFindAll200Response
 */
export interface AnimalControllerFindAll200Response {
    /**
     * 
     * @type {PaginatedAnimalResponseDto}
     * @memberof AnimalControllerFindAll200Response
     */
    data: PaginatedAnimalResponseDto;
    /**
     * 
     * @type {MetaDto}
     * @memberof AnimalControllerFindAll200Response
     */
    meta: MetaDto;
}

/**
 * Check if a given object implements the AnimalControllerFindAll200Response interface.
 */
export function instanceOfAnimalControllerFindAll200Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function AnimalControllerFindAll200ResponseFromJSON(json: any): AnimalControllerFindAll200Response {
    return AnimalControllerFindAll200ResponseFromJSONTyped(json, false);
}

export function AnimalControllerFindAll200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnimalControllerFindAll200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PaginatedAnimalResponseDtoFromJSON(json['data']),
        'meta': MetaDtoFromJSON(json['meta']),
    };
}

export function AnimalControllerFindAll200ResponseToJSON(value?: AnimalControllerFindAll200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': PaginatedAnimalResponseDtoToJSON(value['data']),
        'meta': MetaDtoToJSON(value['meta']),
    };
}

