/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaDto } from './MetaDto';
import {
    MetaDtoFromJSON,
    MetaDtoFromJSONTyped,
    MetaDtoToJSON,
} from './MetaDto';
import type { PaginatedClientResponseDto } from './PaginatedClientResponseDto';
import {
    PaginatedClientResponseDtoFromJSON,
    PaginatedClientResponseDtoFromJSONTyped,
    PaginatedClientResponseDtoToJSON,
} from './PaginatedClientResponseDto';

/**
 * 
 * @export
 * @interface ClientControllerFindAll200Response
 */
export interface ClientControllerFindAll200Response {
    /**
     * 
     * @type {PaginatedClientResponseDto}
     * @memberof ClientControllerFindAll200Response
     */
    data: PaginatedClientResponseDto;
    /**
     * 
     * @type {MetaDto}
     * @memberof ClientControllerFindAll200Response
     */
    meta: MetaDto;
}

/**
 * Check if a given object implements the ClientControllerFindAll200Response interface.
 */
export function instanceOfClientControllerFindAll200Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function ClientControllerFindAll200ResponseFromJSON(json: any): ClientControllerFindAll200Response {
    return ClientControllerFindAll200ResponseFromJSONTyped(json, false);
}

export function ClientControllerFindAll200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientControllerFindAll200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PaginatedClientResponseDtoFromJSON(json['data']),
        'meta': MetaDtoFromJSON(json['meta']),
    };
}

export function ClientControllerFindAll200ResponseToJSON(value?: ClientControllerFindAll200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': PaginatedClientResponseDtoToJSON(value['data']),
        'meta': MetaDtoToJSON(value['meta']),
    };
}

