/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Client } from './Client';
import {
    ClientFromJSON,
    ClientFromJSONTyped,
    ClientToJSON,
} from './Client';
import type { MetaDto } from './MetaDto';
import {
    MetaDtoFromJSON,
    MetaDtoFromJSONTyped,
    MetaDtoToJSON,
} from './MetaDto';

/**
 * 
 * @export
 * @interface ClientControllerCreate201Response
 */
export interface ClientControllerCreate201Response {
    /**
     * 
     * @type {Client}
     * @memberof ClientControllerCreate201Response
     */
    data: Client;
    /**
     * 
     * @type {MetaDto}
     * @memberof ClientControllerCreate201Response
     */
    meta: MetaDto;
}

/**
 * Check if a given object implements the ClientControllerCreate201Response interface.
 */
export function instanceOfClientControllerCreate201Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function ClientControllerCreate201ResponseFromJSON(json: any): ClientControllerCreate201Response {
    return ClientControllerCreate201ResponseFromJSONTyped(json, false);
}

export function ClientControllerCreate201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientControllerCreate201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ClientFromJSON(json['data']),
        'meta': MetaDtoFromJSON(json['meta']),
    };
}

export function ClientControllerCreate201ResponseToJSON(value?: ClientControllerCreate201Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ClientToJSON(value['data']),
        'meta': MetaDtoToJSON(value['meta']),
    };
}

