/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetaDto
 */
export interface MetaDto {
    /**
     * 
     * @type {string}
     * @memberof MetaDto
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof MetaDto
     */
    path: string;
}

/**
 * Check if a given object implements the MetaDto interface.
 */
export function instanceOfMetaDto(value: object): boolean {
    if (!('timestamp' in value)) return false;
    if (!('path' in value)) return false;
    return true;
}

export function MetaDtoFromJSON(json: any): MetaDto {
    return MetaDtoFromJSONTyped(json, false);
}

export function MetaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'path': json['path'],
    };
}

export function MetaDtoToJSON(value?: MetaDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'timestamp': value['timestamp'],
        'path': value['path'],
    };
}

