/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Client } from './Client';
import {
    ClientFromJSON,
    ClientFromJSONTyped,
    ClientToJSON,
} from './Client';
import type { PaginationMetaDto } from './PaginationMetaDto';
import {
    PaginationMetaDtoFromJSON,
    PaginationMetaDtoFromJSONTyped,
    PaginationMetaDtoToJSON,
} from './PaginationMetaDto';

/**
 * 
 * @export
 * @interface PaginatedClientResponseDto
 */
export interface PaginatedClientResponseDto {
    /**
     * 
     * @type {Array<Client>}
     * @memberof PaginatedClientResponseDto
     */
    items: Array<Client>;
    /**
     * 
     * @type {PaginationMetaDto}
     * @memberof PaginatedClientResponseDto
     */
    pagination: PaginationMetaDto;
}

/**
 * Check if a given object implements the PaginatedClientResponseDto interface.
 */
export function instanceOfPaginatedClientResponseDto(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function PaginatedClientResponseDtoFromJSON(json: any): PaginatedClientResponseDto {
    return PaginatedClientResponseDtoFromJSONTyped(json, false);
}

export function PaginatedClientResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedClientResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ClientFromJSON)),
        'pagination': PaginationMetaDtoFromJSON(json['pagination']),
    };
}

export function PaginatedClientResponseDtoToJSON(value?: PaginatedClientResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(ClientToJSON)),
        'pagination': PaginationMetaDtoToJSON(value['pagination']),
    };
}

