/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Animal } from './Animal';
import {
    AnimalFromJSON,
    AnimalFromJSONTyped,
    AnimalToJSON,
} from './Animal';
import type { PaginationMetaDto } from './PaginationMetaDto';
import {
    PaginationMetaDtoFromJSON,
    PaginationMetaDtoFromJSONTyped,
    PaginationMetaDtoToJSON,
} from './PaginationMetaDto';

/**
 * 
 * @export
 * @interface PaginatedAnimalResponseDto
 */
export interface PaginatedAnimalResponseDto {
    /**
     * 
     * @type {Array<Animal>}
     * @memberof PaginatedAnimalResponseDto
     */
    items: Array<Animal>;
    /**
     * 
     * @type {PaginationMetaDto}
     * @memberof PaginatedAnimalResponseDto
     */
    pagination: PaginationMetaDto;
}

/**
 * Check if a given object implements the PaginatedAnimalResponseDto interface.
 */
export function instanceOfPaginatedAnimalResponseDto(value: object): boolean {
    if (!('items' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function PaginatedAnimalResponseDtoFromJSON(json: any): PaginatedAnimalResponseDto {
    return PaginatedAnimalResponseDtoFromJSONTyped(json, false);
}

export function PaginatedAnimalResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAnimalResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AnimalFromJSON)),
        'pagination': PaginationMetaDtoFromJSON(json['pagination']),
    };
}

export function PaginatedAnimalResponseDtoToJSON(value?: PaginatedAnimalResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'items': ((value['items'] as Array<any>).map(AnimalToJSON)),
        'pagination': PaginationMetaDtoToJSON(value['pagination']),
    };
}

