/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMetaDto
 */
export interface PaginationMetaDto {
    /**
     * 
     * @type {number}
     * @memberof PaginationMetaDto
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetaDto
     */
    itemCount: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetaDto
     */
    itemsPerPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetaDto
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetaDto
     */
    currentPage: number;
}

/**
 * Check if a given object implements the PaginationMetaDto interface.
 */
export function instanceOfPaginationMetaDto(value: object): boolean {
    if (!('totalItems' in value)) return false;
    if (!('itemCount' in value)) return false;
    if (!('itemsPerPage' in value)) return false;
    if (!('totalPages' in value)) return false;
    if (!('currentPage' in value)) return false;
    return true;
}

export function PaginationMetaDtoFromJSON(json: any): PaginationMetaDto {
    return PaginationMetaDtoFromJSONTyped(json, false);
}

export function PaginationMetaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMetaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalItems': json['totalItems'],
        'itemCount': json['itemCount'],
        'itemsPerPage': json['itemsPerPage'],
        'totalPages': json['totalPages'],
        'currentPage': json['currentPage'],
    };
}

export function PaginationMetaDtoToJSON(value?: PaginationMetaDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalItems': value['totalItems'],
        'itemCount': value['itemCount'],
        'itemsPerPage': value['itemsPerPage'],
        'totalPages': value['totalPages'],
        'currentPage': value['currentPage'],
    };
}

