/* tslint:disable */
/* eslint-disable */
/**
 * VET API
 * CRM pour vétérinaires
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaDto } from './MetaDto';
import {
    MetaDtoFromJSON,
    MetaDtoFromJSONTyped,
    MetaDtoToJSON,
} from './MetaDto';

/**
 * 
 * @export
 * @interface ResponseDto
 */
export interface ResponseDto {
    /**
     * 
     * @type {object}
     * @memberof ResponseDto
     */
    data: object;
    /**
     * 
     * @type {MetaDto}
     * @memberof ResponseDto
     */
    meta: MetaDto;
}

/**
 * Check if a given object implements the ResponseDto interface.
 */
export function instanceOfResponseDto(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function ResponseDtoFromJSON(json: any): ResponseDto {
    return ResponseDtoFromJSONTyped(json, false);
}

export function ResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'meta': MetaDtoFromJSON(json['meta']),
    };
}

export function ResponseDtoToJSON(value?: ResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'],
        'meta': MetaDtoToJSON(value['meta']),
    };
}

